SDK-705: Provided infrastructure service tests to increase code coverage and quality.
spryker-sdk/sdk pull request #148
Opened 2022-07-12 13:42 UTC by vol4onok

https://spryker.atlassian.net/browse/SDK-705

2022-07-20 15:42 UTC, pavelmaksimov25 requested changes
Please rename test methods with the names like `testGetValueWithOption`  or `testGetValueException` it is hard to understand what it does from the description.

2022-07-20 15:42 UTC, pavelmaksimov25 commented on tests/Sdk/Unit/Extension/Settings/Initializers/ProjectWorkflowInitializerTest.php
> +    public function testReturnWhenWorkflowNotFound(): void
testReturnWhenWorkflowNotFound => testDoesNothingWhenWorkflowNotFound

2022-07-20 15:42 UTC, pavelmaksimov25 commented on tests/Sdk/Unit/Extension/Settings/Initializers/ProjectWorkflowInitializerTest.php
> +    public function testReturnWhenProjectSettingsNotFound(): void
testReturnWhenProjectSettingsNotFound => testDoesNothingWhenProjectSettingsNotFound

2022-07-20 15:42 UTC, pavelmaksimov25 commented on tests/Sdk/Unit/Extension/Settings/Initializers/ProjectWorkflowInitializerTest.php
> +    public function testCreateAndSaveWhenNoExistingWorkflows(): void
it is not clear which case tested from the description. Please, rename

2022-07-21 07:23 UTC, vol4onok commented on tests/Sdk/Unit/Core/Application/Dto/Abstraction/DtoTest.php
> +        $dto = new class extends Dto {
we don't use data list here. it's not need for this test

2022-07-21 08:08 UTC, vol4onok commented on tests/Sdk/Unit/Core/Application/Dto/Abstraction/DtoTest.php
> +    /**
+

2022-07-21 08:08 UTC, vol4onok commented on tests/Sdk/Unit/Extension/Settings/Initializers/CreateDirectoryInitializerTest.php
> +    /**
+

2022-07-21 08:22 UTC, vol4onok commented on tests/Sdk/Unit/Extension/Settings/Initializers/ProjectUuidInitializerTest.php
> +    public function testSetUuidWhenSettingNotFound(): void
renamed to testInitializeWhenSettingNotFound and for other.

2022-07-21 09:57 UTC, sergeyspryker approved these changes

2022-07-21 10:05 UTC, merged