SDK-907: Introduced new interfaces, changed namespaces for contracts …
spryker-sdk/sdk pull request #208
Opened 2022-09-08 08:35 UTC by vol4onok

https://spryker.atlassian.net/browse/SDK-907

2022-09-12 14:34 UTC, sergeyspryker approved these changes

2022-09-14 11:35 UTC, Kyrylo-Meretskyi submitted a review, later dismissed

2022-09-14 11:38 UTC, pavelmaksimov25 requested changes

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/Logger/EventLoggerInterface.php
> +interface EventLoggerInterface
This interface breaks layer dependency direction. A lot of services from the Application layer depend on it. Please, move it to the Application layer.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/ValueReceiver/ReceiverInterface.php
> +interface ReceiverInterface
First, it is not clear what it does in both cases. We need to name it in a more descriptive way, like `InteractionProcessorInterface`. The second, it doesn't belong to the `Infrastructure` layer, must be in the `Application`.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Event/CliRunnerSetupListener.php
> +     * @param \SprykerSdk\Sdk\Infrastructure\Service\CommandRunner\LocalCliRunner $cliRunner
It must be depended on the abstraction. Please change it to the `CommandRunnerInterface` interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/ActionApprover.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the `ReceiverInterface` interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/CommandRunner/CommandRunnerInterface.php
> +interface CommandRunnerInterface
This one is used in the Application layer. Please move it to the `Application` layer

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/Initializer.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the ReceiverInterface interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/ValueReceiver/CliReceiver.php
> +class CliReceiver implements ReceiverInterface, InputOutputReceiverInterface
Already answered in the comment to the `ReceiverInterface`

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/WorkflowRunner.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the `ReceiverInterface` interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Presentation/Console/Command/InitProjectCommand.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the `ReceiverInterface` interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Presentation/Console/Command/RunWorkflowCommand.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the `ReceiverInterface` interface.

2022-09-14 11:38 UTC, pavelmaksimov25 commented on src/Presentation/Console/Command/ShowWorkflowCommand.php
> +    protected CliReceiver $cliValueReceiver;
It must be depended on the abstraction. Please change it to the `ReceiverInterface` interface.

2022-09-15 14:02 UTC, pavelmaksimov25 approved these changes

2022-09-15 14:03 UTC, sergeyspryker approved these changes

2022-09-16 12:22 UTC, merged