SDK-982 refactor project setting repository
spryker-sdk/sdk pull request #223
Opened 2022-09-28 11:01 UTC by sergeyspryker

2022-09-29 08:22 UTC, pavelmaksimov25 commented
Missed ticket number in the PR description.

2022-10-03 11:11 UTC, Kyrylo-Meretskyi approved these changes

2022-10-05 10:55 UTC, vol4onok commented on src/Extension/Setting/Initializer/ProjectWorkflowInitializer.php
> +        Registry $workflows
`Registry $workflowRegistry`

2022-10-06 14:48 UTC, vol4onok approved these changes

2022-10-17 10:45 UTC, pavelmaksimov25 requested changes

2022-10-18 13:52 UTC, merged

2022-10-18 13:52 UTC, pavelmaksimov25 commented
dev qa should be done in the SDK-848