SDK-1125: Created project path for API
spryker-sdk/sdk pull request #261
Opened 2022-11-03 13:41 UTC by vol4onok

For changing project dir you need to recreate containers from the concrete project path. just run again `spryker-sdk rest-api-start`

2022-11-03 13:51 UTC, sergeyspryker requested changes

2022-11-03 13:51 UTC, sergeyspryker commented on public/index.php
> +chdir('/project');
$projectDir = getenv('SDK_PROJECT_DIR');

if ($projectDir !== false) {
    chdir(projectDir);
}

2022-11-03 13:54 UTC, sergeyspryker submitted a review, later dismissed

2022-11-03 15:25 UTC, sergeyspryker approved these changes

2022-11-03 16:09 UTC, pavelmaksimov25 approved these changes

2022-11-16 14:22 UTC, pavelmaksimov25 approved these changes

2022-11-16 14:22 UTC, merged