SDK-1281: Fixed output report style
spryker-sdk/sdk pull request #287
Opened 2022-11-24 13:58 UTC by vol4onok

## Describe your changes

## Issue ticket link
Ticket: https://spryker.atlassian.net/browse/SDK-1281.

## Checklist before requesting a review
- [ ] I have added ticket link to the PR description.
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2022-11-24 14:02 UTC, sergeyspryker requested changes

2022-11-24 14:02 UTC, sergeyspryker commented on src/Infrastructure/Violation/Formatter/OutputViolationReportFormatter.php
> +                            $fileViolation->getMessage() ?: 'n/a',
Move `n/a` into the constant pls

2022-11-24 14:12 UTC, sergeyspryker submitted a review, later dismissed

2022-11-24 14:22 UTC, pavelmaksimov25 requested changes

2022-11-28 08:29 UTC, pavelmaksimov25 approved these changes

2022-11-30 10:31 UTC, pavelmaksimov25 approved these changes

2022-11-30 10:48 UTC, pavelmaksimov25 approved these changes

2022-11-30 10:49 UTC, merged