Feature/sdk 1356 version file usage and context
spryker-sdk/sdk pull request #295
Opened 2022-11-30 14:33 UTC by vol4onok

## Describe your changes

## Issue ticket link
Ticket: https://spryker.atlassian.net/browse/SDK-1356.

## Checklist before requesting a review
- [ ] I have added ticket link to the PR description.
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2022-12-01 09:44 UTC, sergeyspryker requested changes

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/EventListener/ContextOutputCommandListener.php
> +class ContextOutputCommandListener
In not sure that it should be there. I can see there are console specific things. May be move it into the presentation console layer?

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/EventListener/ContextOutputCommandListener.php
> +        $template = [
Move array with templates into the constant pls.

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/Resources/config/services.yaml
> +            - {
Shouldn't use `{` `}` in yaml multiline syntax

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/Service/LifecycleManager.php
> +        if ($this->environment !== 'prod') {
Why is version checking is prohibit for dev? Also we have `test` env for ci

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/Service/LifecycleManager.php
> +            return [new Message('Could not find `VERSION` file, skip updatable check')];
Minor: move `VERSION` into the constant and use it in messages and in `$versionFilePath` var

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/Service/LifecycleManager.php
> +            return [new Message('Could not find version in the file `VERSION`. File is empty.')];
Same

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/EventListener/ContextOutputCommandListener.php
> +        return MessageInterface::ERROR;
Why is the normal verbosity is Error?

2022-12-01 09:44 UTC, sergeyspryker commented on src/Infrastructure/EventListener/ContextOutputCommandListener.php
> +        if ($output->isVerbose()) {
You can use mapping:
```
[
    OutputInterface::VERBOSITY_VERBOSE => MessageInterface::SUCCESS,
    .....
]
```

2022-12-01 09:50 UTC, sergeyspryker requested changes

2022-12-01 09:50 UTC, sergeyspryker commented on bin/spryker-sdk.sh
> +    exit 0
remove exit

2022-12-01 09:54 UTC, sergeyspryker commented on bin/spryker-sdk.sh
> +    exit 0
git describe --abbrev=0 --tags > VERSION

2022-12-01 10:17 UTC, Kyrylo-Meretskyi commented on src/Presentation/Console/Command/UpdateCommand.php
> +            $context->addMessage('check_updates_' . $key, $message);
Move `check_updates_` to const

2022-12-01 11:06 UTC, vol4onok commented on src/Infrastructure/EventListener/ContextOutputCommandListener.php
> +        return MessageInterface::ERROR;
I removed it. Checked only debug

2022-12-01 11:07 UTC, vol4onok commented on src/Presentation/Console/Command/UpdateCommand.php
> +            $context->addMessage('check_updates_' . $key, $message);
Don't need it. it's not const value.

2022-12-01 11:30 UTC, sergeyspryker commented on bin/spryker-sdk.sh
> +    git describe --abbrev=0 --tags > $SDK_DIR/VERSION
I guess it show version of target ptoject not sdk. Need to point sdk folder.

2022-12-01 12:04 UTC, sergeyspryker approved these changes

2022-12-02 08:14 UTC, pavelmaksimov25 approved these changes

2023-02-20 08:20 UTC, pavelmaksimov25 commented on src/Infrastructure/Service/LifecycleManager.php
> +    protected string $environment;
Not in use

2023-02-20 08:42 UTC, pavelmaksimov25 commented on src/Core/Application/Service/ContextFactory.php
> +    public function hasContext(): bool
Missed unit tests

2023-02-20 10:05 UTC, pavelmaksimov25 submitted a review, later dismissed

2023-03-07 08:14 UTC, pavelmaksimov25 approved these changes

2023-03-07 08:14 UTC, merged