SDK-1309 add task set sub-tasks relations
spryker-sdk/sdk pull request #296
Opened 2022-11-30 16:52 UTC by sergeyspryker

## Describe your changes

## Issue ticket link
Ticket:[SDK-1309](https://spryker.atlassian.net/browse/SDK-1309)

## Checklist before requesting a review
- [ ] I have added ticket link to the PR description.
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2022-12-01 07:54 UTC, vol4onok commented on src/Core/Application/Dependency/Repository/TaskSetTaskRelationRepositoryInterface.php
> +interface TaskSetTaskRelationRepositoryInterface
Do we need this repo for one-to-many? Can we resolve it with annotations in task model?

2022-12-01 07:56 UTC, vol4onok commented on src/Infrastructure/Mapper/TaskSetTaskRelationMapper.php
> +    protected TaskMapperInterface $taskMapper;
annotation

2022-12-01 08:00 UTC, vol4onok commented on src/Presentation/Console/Command/TaskRunFactoryLoader.php
> +    protected TaskSetTaskRelationRepositoryInterface $taskSetTaskRelationRepository;
annotation

2022-12-01 08:08 UTC, vol4onok commented on src/Infrastructure/Repository/TaskSetTaskRelationRepository.php
> +    protected TaskSetTaskRelationMapperInterface $taskSetTaskRelationMapper;
annotation

2022-12-01 08:20 UTC, vol4onok approved these changes

2022-12-02 12:09 UTC, pavelmaksimov25 requested changes
Please provide unit tests for the `Mapper` and acceptance test to check the decorated help message in the output.

2022-12-02 12:09 UTC, pavelmaksimov25 commented on tests/Sdk/Unit/Infrastructure/Builder/TaskSet/TaskSetTaskRelationsBuilderTest.php
> +        $this->expectException(InvalidArgumentException::class);
// Assert

The same for the method above and the rest of new tests with the exception checks.

2022-12-05 08:59 UTC, vol4onok commented on src/Presentation/Console/Command/TaskRunFactoryLoader.php
> +    protected TaskSetTaskRelationRepositoryInterface $taskSetTaskRelationRepository;
probably yes. CS sometime passes some issues.

2022-12-05 09:51 UTC, pavelmaksimov25 submitted a review, later dismissed

2022-12-05 14:46 UTC, pavelmaksimov25 approved these changes

2022-12-08 08:48 UTC, pavelmaksimov25 approved these changes

2022-12-08 08:49 UTC, merged