SDK2283: Added evaluator bundle
spryker-sdk/sdk pull request #368
Opened 2023-05-23 14:58 UTC by vol4onok

## Describe your changes

## Issue ticket link
Ticket: https://spryker.atlassian.net/browse/SDK-2283.

## Checklist before requesting a review
- [ ] I have added ticket link to the PR description.
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2023-05-23 16:33 UTC, pavelmaksimov25 approved these changes
All good, but do not forget to test how this branch installs into the b2c demoshop or b2b demoshop before merge.

2023-05-23 16:33 UTC, pavelmaksimov25 submitted a review, later dismissed
All good, but do not forget to test how this branch installs into the b2c demoshop or b2b demoshop before merge.

2023-05-24 08:22 UTC, sergeyspryker requested changes

2023-05-24 08:22 UTC, sergeyspryker commented on composer.json
> +        {"type": "vcs", "url":  "git@github.com:spryker-sdk/evaluator.git"}
extra space, and add spaces after/after { }

2023-05-24 08:23 UTC, sergeyspryker approved these changes

2023-05-26 11:18 UTC, pavelmaksimov25 approved these changes

2023-05-26 11:18 UTC, merged