SDK-294: Increase code coverage
spryker-sdk/sdk pull request #47
Opened 2022-01-06 12:15 UTC by Kyrylo-Meretskyi

2022-01-19 11:31 UTC, vol4onok commented on src/Core/Appplication/Service/CommandExecutor.php
> -    /**
I remember I've removed this file

2022-01-19 12:29 UTC, Kyrylo-Meretskyi commented on src/Core/Appplication/Service/CommandExecutor.php
> -    /**
I updated the branch

2022-01-19 15:13 UTC, vol4onok approved these changes

2022-01-19 15:13 UTC, vol4onok commented on tests/Sdk/Tests/Infrastructure/Repository/TaskYamlRepositoryTest.php
> +        // Arrange
// Assert
 i think it can be in other places

2022-01-19 15:13 UTC, vol4onok commented on tests/Sdk/Tests/Infrastructure/Repository/TaskYamlRepositoryTest.php
> +
// Assert

2022-01-19 15:13 UTC, vol4onok commented on tests/Sdk/Tests/Infrastructure/Repository/TaskYamlRepositoryTest.php
> +        // Arrange
the same

2022-01-21 08:54 UTC, vol4onok requested changes
Don't push needs to push bugfixing branch before

2022-01-24 09:54 UTC, Kyrylo-Meretskyi commented on tests/Sdk/Tests/Infrastructure/Repository/TaskYamlRepositoryTest.php
> +
Fixed

2022-01-24 09:54 UTC, Kyrylo-Meretskyi commented on tests/Sdk/Tests/Infrastructure/Repository/TaskYamlRepositoryTest.php
> +        // Arrange
Fixed

2022-01-24 14:59 UTC, merged