Feature/improved create pbc task
spryker-sdk/sdk pull request #99
Opened 2022-05-08 13:15 UTC by newLoki

Creating a PBC through the sdk (`spryker-sdk generate:php:pbc`) only created an outdated PBC boilerplate that wasn't even compatible with the newest docker/sdk and the spryker/aop-sdk.
Goal here is to have a fully working project set up after the task has run.

This pull request will:

- fix naming of the composer project
- update all depenencies, based on PHP 7.4 (optional `spryker-sdk generate:php:pbc --pbc_php_version=8.0` will use PHP 8)
- Ensure the docker/sdk environment of the PBC has a different namespace as the spryker demoshop as they would share the same mutagen/docker-sync container if the namespace is the same and code would be synchronized between different projects
- Install docker/sdk to the newly created PBC

Another thing I noticed using the SDK, the build https://github.com/spryker-sdk/sdk/releases/tag/0.1.1 is not installable at all. The current master is installable, so it would be great to build a new installer and publish it.

2022-05-09 08:23 UTC, stereomon requested changes

2022-05-09 08:23 UTC, stereomon commented on src/Extension/Tasks/Commands/NextPbcStepsCommand.php
> +        $message = 'Run "cd %s && docker/sdk boot -s deploy.dev.yml" and follow the instructions to spin up the local environment and follow the instructions';
```suggestion
        $message = 'Run "cd %s && docker/sdk boot -s deploy.dev.yml" and follow the instructions to spin up the local environment';
```

2022-05-09 08:23 UTC, stereomon commented on src/Extension/Tasks/Commands/NextPbcStepsCommand.php
> +class NextPbcStepsCommand implements ExecutableCommandInterface
A class doc block could help to understand what this class is for.

2022-05-18 06:22 UTC, stereomon commented
@vol4onok Can you take care of getting this merged as well?

2022-05-18 09:29 UTC, merged

2022-05-18 10:35 UTC, vol4onok commented
Thanks for the PR. it was processed here with merging and fixing https://github.com/spryker-sdk/sdk/pull/103